[build]
publish = "public"
functions = "netlify/functions"

[[redirects]]
from = "/webhook"
to = "/.netlify/functions/webhook"
status = 200

[[redirects]]
from = "/webhook-test"
to = "/.netlify/functions/webhook-test"
status = 200